### ISSUE TITLE
bug: 使用 JsonSchemaUtils 工具类生成资源实例的 Schema 报错

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-audit-java-sdk#9]
异常信息
```
Caused by: java.lang.ExceptionInInitializerError: null
        at com.tencent.bk.job.manage.api.iam.impl.IamTaskPlanCallbackResourceImpl.fetchResourceTypeSchemaResp(IamTaskPlanCallbackResourceImpl.java:205)
        at com.tencent.bk.job.common.iam.service.BaseIamCallbackService.baseCallback(BaseIamCallbackService.java:137)
        at com.tencent.bk.job.manage.api.iam.impl.IamTaskPlanCallbackResourceImpl.callback(IamTaskPlanCallbackResourceImpl.java:198)
        at com.tencent.bk.job.manage.api.iam.impl.IamTaskPlanCallbackResourceImpl$$FastClassBySpringCGLIB$$3e51bd5e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.tencent.bk.job.common.iam.aspect.IamCallbackAspect.logBeforeProcessCallbackRequest(IamCallbackAspect.java:46)
        ... 79 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.<init>(JsonSchemaGenerator.java:38)
        at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.<init>(JsonSchemaGenerator.java:33)
        at com.tencent.bk.audit.utils.json.JsonSchemaUtils.<clinit>(JsonSchemaUtils.java:14)
        ... 89 common frames omitted
```

**Comment by wangyu096** [comment]
问题分析：JsonSchemaGenerator构造函数传入 null，导致空指针。

```
package com.tencent.bk.audit.utils.json;

import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.jsonSchema.JsonSchema;
import com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator;
import lombok.extern.slf4j.Slf4j;

/**
 * JsonSchema 工具
 */
@Slf4j
public class JsonSchemaUtils {
    private static final JsonSchemaGenerator JSON_SCHEMA_GENERATOR = new JsonSchemaGenerator((ObjectMapper) null);
}

```
